# Generated by Django 3.1.4 on 2020-12-30 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('nationality', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=75)),
                ('id_type', models.CharField(choices=[('N', 'national id'), ('P', 'passport')], max_length=1)),
                ('id_numbers', models.CharField(max_length=14)),
                ('hire_date', models.DateField(verbose_name='hire_date')),
                ('emp_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('place_of_birth', models.CharField(max_length=75)),
                ('social_status', models.CharField(choices=[('M', 'married'), ('S', 'single')], max_length=1)),
                ('mobile_number', models.CharField(max_length=11)),
                ('insured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('has_medical', models.BooleanField(default=False)),
                ('balance', models.IntegerField(blank=True, default=21, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
