# Generated by Django 3.1.4 on 2020-12-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(default=None, verbose_name='hire_date'),
        ),
    ]
