# Generated by Django 3.1.4 on 2020-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='balance',
            field=models.IntegerField(default=21),
        ),
    ]
