# Generated by Django 3.1.4 on 2020-12-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.IntegerField(blank=True, default=21, null=True),
        ),
    ]
