# Generated by Django 3.1.4 on 2020-12-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20201231_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
