# Generated by Django 3.1.4 on 2020-12-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20201231_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=None, null=True, verbose_name='date_of_birth'),
        ),
    ]
