# Generated by Django 3.1.4 on 2020-12-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('contracts', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.department')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('pos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.position')),
            ],
        ),
    ]
