# Generated by Django 3.1.4 on 2020-12-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('contracts', '0003_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dep_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.department'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.position'),
        ),
    ]
