# Generated by Django 3.1.4 on 2020-12-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20201227_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.department'),
        ),
    ]
