# Generated by Django 3.1.4 on 2021-01-05 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=55)),
                ('leave_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confirm', models.CharField(blank=True, choices=[('w', 'waiting'), ('a', 'accepted'), ('r', 'rejected')], default='w', max_length=1, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavemaster')),
            ],
        ),
    ]
