# Generated by Django 3.1.4 on 2020-12-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confirm', models.CharField(choices=[('w', 'waiting'), ('a', 'accepted'), ('r', 'rejected')], max_length=1)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('leave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavemaster')),
            ],
        ),
    ]
